### ISSUE TITLE
Support for Multi-Value Dimensions

### ISSUE THREAD

**Issue by ShrillP** [rovio/rovio-ingest#40]
Is there support or will there be future support for dimensions that have multiple values (e.g. arrays of strings)? I was running into an issue when trying to run the No-code wrapper script provided by the rovio-ingest repository but ran into an error when it was trying to ingest a column that has a value of a string array. 

**Error Message:**
- `pyspark.errors.exceptions.captured.IllegalArgumentException: Dimensions with unsupported data types, set excludeColumnsWithUnknownTypes to true to exclude: StructField(colName,ArrayType(StringType,true)`

**Example of the data I am trying to work with:**
- "tags": ["t1","t2","t3"]

**Comment by vivek-balakrishnan-rovio** [comment]
Hi,
There is no support yet for multivalued dimension yet.
We would be working on it after our summer breaks.
If you would be also willing to implement it we would be glad to review a pull request and merge it

**Comment by mpasa** [comment]
I've done this before but using an `OnHeapIncrementalIndexer`. The only trick is that Spark uses `WrappedArray`s that need to be transformed back to Java `List`s. Like this example in Scala:

```
new MapBasedInputRow(
  row.getAs[Long](timestampField),
  dimensions,
  columns
    .map { name =>
      // Spark's arrays (WrappedArray) should be converted to Java
      // lists to allow multi-value dimensions
      val value = row.getAs[Object](name) match {
        case v: Seq[_] => v.asJava
        case v         => v
      }
      name -> value
    }
    .toMap
    .asJava
)
```
