### ISSUE TITLE
Support for hdfs storage

### ISSUE THREAD

**Issue by fabricebaranski** [rovio/rovio-ingest#47]
Do you plan to add hdfs storage?

**Comment by vivek-balakrishnan-rovio** [comment]
Hi @fabricebaranski,
I will add support for Hdfs storage, however, can you please help us test it with a real cluster?

**Comment by fabricebaranski** [comment]
Hi @vivek-balakrishnan-rovio,
I will be happy to test it.
I am already testing a version I developped based on your code with hdfs storage. 
Once is validated from my side, I can submit it.

**Comment by vivek-balakrishnan-rovio** [comment]
We are open to contributions & if you can contribute that would be awesome :)

**Comment by vivek-balakrishnan-rovio** [comment]
@fabricebaranski Here is a draft PR for HDFS support https://github.com/rovio/rovio-ingest/pull/48
can you please test it.

 In case, if you would like to make a contribution, you would need sign a [contributor license agreement](https://github.com/rovio/rovio-ingest/blob/main/CONTRIBUTING.md#contributor-license-agreement).
Please let me know how you would like to proceed
